hd-zero/hdzero-vtx

.gitignore
src/common.h
src/hardware.c
src/isr.c
src/isr.h
src/monitor.c
src/monitor.h
src/msp_displayport.c
src/print.c
src/print.h
src/sfr_def.h
src/sfr_ext.h
src/toolchain.h
src/uart.c
src/uart.h

builds on #4 
adds macros for the different compiler intrinsics in use, to enable compilation with compilers other than Keil.
compilation with keil was validated. effective code stays the same.

add toolchain macros to enable cross compiler compatibility 

---

.clang-format

with platformio in place, clang-format can be utilized to enforce consistent code formatting across the codebase.
this PR adds a appropriate configuration file.

add clang-format file

---

.clang-format
script/pre_script.py
src/camera.c
src/global.c
src/global.h
src/hardware.c
src/isr.c
src/mcu.c
src/sfr_def.h
src/smartaudio_protocol.c

builds on #8
this PR includes the minimal amount of changes to enable compilation on sdcc 
_with `INIT_VTX_TABLE` disabled_, it does not fit into flash with that enabled _yet_
it is however not yet operational.
most of the commits were originally authored by @saidinesh5 and have been refined by @pjpei and myself
compilation and correct operation on Keil was verified by myself.

enable compilation on sdcc

---

script/post_script.py
script/sdcc_map.py

* Takes in a .map file generated by the linker stage of sdcc and calculates the sizes of symbols, sections and modules. Results are output in csv format as: 
`<firmware name>.map.<symbols|sections|modules>.csv`
`python sdcc_map.py <path to map file>` 
`pio run -t sdcc_map`
| Bytes | Symbol                     | Module              | Address | Section | SectionType |
| ----- | -------------------------- | ------------------- | ------- | ------- | ----------- |
| 5742  | _DM6300_init7              | dm6300              | 0x6f39  | CSEG    | CODE        |
| 3788  | _camStatusUpdate           | camera              | 0x2956  | CSEG    | CODE        |
| 2551  | _DM6300_init2              | dm6300              | 0x570b  | CSEG    | CODE        |
| 2376  | _DM6300_EFUSE2             | dm6300 …

Script to parse sdcc.map files and collect size and location information for all global symbols

---

platformio.ini
src/common.h
src/dm6300.c
src/dm6300.h
src/hardware.c
src/hardware.h
src/i2c_device.c
src/i2c_device.h
src/mcu.c
src/msp_displayport.c
src/msp_displayport.h
src/smartaudio_protocol.c

The bug will cause the VTX to eventually fail to output the expected RF power, the actual RF power will be 2~3dBm lower, and the temperature compensation function will be lost.
Temperature Compensation: When the VTX heats up, the VTX increases the RF output power to counteract thermal decay within a certain temperature range.

Fix dm6300 get tempurature

---

src/common.h
src/global.h
src/mcu.c
src/msp_displayport.c
src/version.h

- Use semver.
- VTX_NAME align left.
- Modify debug information when VTX power up.
- Vtx version number transfer to VRX is being verified.

Version control with semvers

---

src/dm6300.c

Temporarily solve the problem that the VTX temperature compensation is too low due to the inaccurate initial temperature value of dm6300.

Temporarily solve dm6300 initial tempureture value too low.

---

src/hardware.c
src/msp_displayport.c

When using MSP VTX, the issue causes rainbows to appear on the armed momentary screen.

fix msp vtx bug

---

src/msp_displayport.c

- improves msp identifier handling
- adds support of the `quic` identifier (https://github.com/BossHobby/QUICKSILVER)
- adds hack for msp support _and_ ardupilot font on the `quic` identifier
hack can be dropped once there is another way to select a font on the VRX

improve msp identifier handling, add hack to get msp vtx & ardu font for quic

---

src/msp_displayport.c

VRX load osd font image only once when it receives fc_variant != 0xffffffff

change fc_variant initial value to 0xff 0xff 0xff 0xff

---

platformio.ini
src/msp_displayport.c

builds on #61
- improve clarity of fc_lock check
- remove quic font workaround
- add monitor speed to pio config, allows 1-click read of debug output in vscode

Remove quic font workaround & misc

---

src/camera.c
src/camera.h
src/hardware.c
src/hardware.h
src/i2c_device.c
src/msp_displayport.c
src/runcam.c
src/runcam.h

- For runcam camera, if video format is changed, users no longer need to repower VTX.
- The nano 90 camera has not yet completed verification.

reset runcam camera isp if video format is changed

---

src/common.h
src/hardware.c
src/mcu.c
src/msp_displayport.c

- For VTX with SA port:
- Enable msp vtx, initialize RF delay about 3-4 seconds.
- Disable msp vtx and SA, initialization RF delay is expected to be 5 seconds (if vtx works as expected).
- When SA is enabled, the initial RF delay is still 10 seconds.
- For VTX without SA port (whoop vtx):
- Enable msp vtx, initialize RF delay about 3-4 seconds.
- Disable msp vtx, the initial RF delay is expected to be 5 seconds (if vtx works as expected).

Optimize power on init RF delay

---

src/camera.h
src/i2c.c
src/mcu.c
src/runcam.c
src/runcam.h

For the runcam nano90 camera, the custom shutter speed cannot take effect when the power is turned on, the reason is unknown.
The current remedy is to configure the shutter speed again about three seconds after the system starts.

Fix runcam shutter set for runcam nano90

---

src/common.h
src/dm6300.c
src/dm6300.h
src/msp_displayport.c
src/msp_displayport.h
src/smartaudio_protocol.c
src/smartaudio_protocol.h

Firmware is supporting only band and channel setting at the moment even the direct frequency is also possible.
It should be also possible to set and save used channel to FC before even plugin power for VTX (e.g. on races using Configurator without battery plugged in). This is not possible at the moment when VTX_MSP is used. VTX overrides new values using last settings on boot.  
This PR fixes two issues:
1) the direct frequency control.
2) FC can set used band and channel (or freq) on boot and VTX uses those if values are valid.

Fix VTX_MSP frequency control

---

src/msp_displayport.c

The current firmware prevents MSP-VTX messages from being parsed if init_tables_done = 0, but init_tables_done = 1 can only be set if InitVtxTable is called.
InitVtxTable is only called for BTFL or QUIC.
INAV does not have the concept of VTX tables, this PR allows INAV's MSP_SET_CONFIG messages to be processed.
The check for INAV when setting init_table_unsupported can potentially be dropped to prevent similar pull requests from being needed in the future.
If you would like to help test this pull request, you will need to flash a version of INAV 7.0.0 that includes https://github.com/iNavFlight/inav/pull/9166 and a VTX firmware that includes this pull request.
For instructions on how to download INAV firmware including that pull request, please refer to [INAV's …

Allow MSP-VTX to work with INAV

---

src/monitor.c
src/msp_displayport.c

When FC armed, VTX will maintain at 25mw most of the time.
I thought betaflight would send the original power level to VTX, I was wrong. Betaflight will modify the power level according to g_is_armed and then send it to VTX.

fix MSP VTX lp mode

---

src/msp_displayport.c

This problem will cause channel or band to be confused when using iNav 6.x.x.

check warning band and channel for msp vtx

---

src/hardware.c
src/hardware.h
src/msp_displayport.c
src/msp_displayport.h

VTX enter/exit 0mw mode conflicts with some FC stick commands even though most people do not use FC stick commands. We added an option called shortcut to the vtx menu to modify the shortcut of enter/exit 0mw mode to avoid conflicts.
`shortcuts <OPT_A or OPT_B>`
Options：
- OPT_A. As default.
- OPT_B.

vtx menu add new item for stick command mode

---

src/common.h
src/dm6300.c
src/hardware.c
src/hardware.h
src/msp_displayport.c
src/msp_displayport.h
src/smartaudio_protocol.c
src/tramp_protocol.c

Japan needs this.
- E1: 5705
- F1: 5740

add channel E1 and F1

---

src/msp_displayport.c

If the shortcut is OPT_B, when using the shortcut key to enter 0mw, the shortcut will be saved as OPT_A by mistake.

fix shortcut

---

src/hardware.c

- VTX supports 115200 and 230400 baud rates.
- If VTX does not receive the msp packet correctly for more than 10 seconds after powering on, VTX will configure uart to another baud rate the next time it is powered on.

set uart baudrate only when init

---

src/camera.c
src/common.h
src/hardware.c

- Short-circuit TX and RX before powering on at VTX side.
- Power on VTX, VTX detects the sequence sent from TX on RX, and then initializes all parameters.
- Wait 5 seconds and then power off. At this time, all parameters have been initialized.

reset config via short circuit TX and RX

---

src/hardware.c
src/msp_displayport.c
src/msp_displayport.h

To auto switch baud rate(115200/230400) only when init
In the past, VTX would always send msp packets to FC after it was powered on. If the baud rates of VTX and FC did not match, the erroneous data received by FC might cause it to enter cli mode.
Now:
- VTX will not start sending msp packets from power on until it receives the correct msp data packet.
- If VTX does not receive the correct data packet for more than 2 seconds, it will switch the baud rate and continue to receive. Until the correct data packet is received, the serial port baud rate will be locked and start sending msp data packets.
- If FC changes the baud rate after the baud rate is locked, VTX will not automatically detect the baud rate again unless powered on again.
Note HDZero Race v3 VTX only supports 115200 in order …

check msp packet rx before sending msp request

---

src/common.h
src/hardware.c

For some vtx, uart loopback does not seem to take effect.

reset config via define RESET_CONFIG

---

src/camera.c
src/msp_displayport.c
src/runcam.c

As described in the title, this PR adds the possibility to flip the image only horizontally or only vertically.
Now the HV FLIP option in cam menu has four possible values:
- OFF
- ON
- V ONLY
- H ONLY
This feature has been added to give more flexibility and it has been suggested by some users on Discord.
Tested on a Race V2 + Runcam Nano V2
https://github.com/hd-zero/hdzero-vtx/assets/32413980/4f56e006-2e96-4a9f-84c3-228970557011

Cam menu option to flip only horizontally or only vertically

---

src/hardware.c
src/isr.c
src/mcu.c
src/uart.c
src/uart.h

This PR is used to solve the OSD freeze problem after VTX is powered on.
- Cause:
- The initial baud rate of VTX is 230400 and that of FC is 115200.
- After power-on, `CPU_init()` will initialize the uart to 115200 and immediately enable interrupt.
- VTX executes `Init_HW()`. During this period, the serial port receives some msp packages (115200) from FC.
- VTX sets the baud rate to 230400(eeprom saved) at the end of Init_HW().
- VTX enters the `while(1)` loop and parses the complete msp package, mistakenly thinking that the baud rate of FC is 230400.
- After that, VTX can no longer receive the correct msp package due to the baud rate mismatch.
- Solution:
- Do not enable interrupts during `CPU_init()`.
- Initialize the uart bardate(eepram saved) earlier to avoid losing data. Then enable …

Initialize uart first, then enable interrupt

---

src/hardware.c

This is gives more detail about the rationale behind why we use an unusual timing gap for off pulse.
This may be useful because the point of the the LED diagnostic framework is that it allows other patterns to be added in future if necessary and consistency is essential.

clarify mark space separation rationale for LED diagnostic encoding (comments)

---

src/msp_displayport.c

On startup, the initial MSP_VARIANT message MUST be processed before the MSP_VTX_CONFIG message.
If this does not happen, the VTX will/may not register properly with the FC and potentially discard further MSP messages.
This change will ensure the initial messages are processed in order.
Process Initial MSP messages in the correct order.

Process Initial MSP messages in the correct order.

---

src/msp_displayport.c
src/msp_displayport.h

EmuFlight reported an issue with the latest VTX code.
For the VTX to communicate with an FC, an MSP_VTX_CONFIG handshake is done to sync the two devices.
If the FC is not interested in controlling the VTX band/channel/power, it still needs to send a response to the VTX when requested. This is achieved by sending an MSP_VTX_CONFIG message with an invalid VTX ID (6 is MSP).
This change detects this invalid message Id and throws the message away.

Drop MSP_VTX_CONFIG messages with an invalid VTX id

---

src/uart.c

Moved #endif past redundant code when USE_TRAMP is defined.

Update uart.c -resolve USE_TRAMP build warnings (race v3)

---

src/camera.c
src/camera.h
src/common.h
src/hardware.c
src/i2c_device.c
src/i2c_device.h
src/lifetime.c
src/lifetime.h
src/msp_displayport.c
src/msp_displayport.h
src/msp_protocol.h
src/runcam.c
src/runcam.h
src/version.h

**Add control for 2 and 3 camera switches.**
Use CAMERA CONTROL 1 to select a camera on a 2 camera switch.
Use CAMERA CONTROL 2 to select camera 3 on a 3 camera switch.
Disable camera control when in camera menu and switch detected.
Assign each camera profile to each camera on the switch (ex, profile 1 for camera 1) when switch detected.
Synchronize video mode across all profiles when switch detected.
Display switch type detected on the VTX menu.
Display camera type detected on the VTX menu.
**Additional.**
Ensure Nano90 HV Flip is actioned when changed in the camera menu (will only change on save/exit at this time).
Use BOXID to determine location of ARM flag in status messages.
Correct spelling and/or clarify some function names and variables.
Add an UNUSED(param) definition to avoid …

Camera control

---

script/sdcc_map.py

Fix Python regex syntax error:
````
.../hdzero-vtx/script/sdcc_map.py:82: SyntaxWarning: invalid escape sequence '\s'
sectionHeaderRegex = re.compile("(?P<name>.*?)\s+(?P<address>.*?)\s+(?P<sizeHex>.*?)\s=\s+(?P<sizeBytes>\d+)\.\sbytes\s\((\w+),(\w+),(?P<type>\w+)\)")
.../hdzero-vtx/script/sdcc_map.py:83: SyntaxWarning: invalid escape sequence '\s'
symbolReg = re.compile("(?P<type>C|D):\s+(?P<address>.*?)\s+(?P<name>\w+)\s+(?P<module>\w+|.*)")
````

Fix SDCC map regex + some minor formatting
