.gitignore
boards/DM5680.json
platformio.ini
script/post_script.py
script/pre_script.py
src/common.h

Adds a platformio configuration, _does not build yet_.
Keil compilation was verified. No code changes of any significance.

add platformio configuration

---

.clang-format
.gitignore
boards/DM5680.json
platformio.ini
script/external/send.py
script/external/xmodem.py
script/pre_script.py

- addresses code-formatting preferences as brought up on discord (4 spaces)
- corrects the board definition as supplied to pio
- adds a custom upload script

Configuration fixups

---

.github/workflows/build.yml

adds a github action workflow for automatic builds and artifact uploads. 
built binaries can be download from the action summary.
partially ripped off @cruwaller 's openvtx yaml.

Add GitHub Action Worflow

---

src/camera.h
src/common.h
src/dm6300.h
src/global.h
src/hardware.c
src/hardware.h
src/isr.h
src/lifetime.h
src/monitor.c
src/monitor.h
src/msp_displayport.c
src/msp_displayport.h
src/print.h
src/smartaudio_protocol.h
src/spi.c
src/stdint.h
src/uart.h

This PR fixes both SDCC and Keil compiler warnings and unifies include guards across the codebase.

fix compiler warnings

---

src/camera.c
src/dm6300.c
src/hardware.c
src/hardware.h
src/i2c.c
src/i2c.h
src/i2c_device.c
src/isr.c
src/isr.h
src/lifetime.c
src/mcu.c
src/monitor.c
src/rom.c

- reworks i2c functions into 8 and 16 bit variants to reduce per-call overhead
- moves flags to bit type to save on memory
- moves strings in camera.c to static arrays for tighter packing

More micro optimizations

---

src/camera.c
src/camera.h
src/common.h
src/mcu.c
src/msp_displayport.c
src/msp_displayport.h

Merge auto profile and manual profile in camera menu

modify camera menu

---

src/msp_displayport.c

Not sure if that fixes the osd disappearing issue.

fix parse_displayport() function

---

platformio.ini
src/common.h
src/dm6300.c
src/dm6300.h
src/hardware.c
src/hardware.h
src/i2c_device.c
src/i2c_device.h
src/msp_displayport.c
src/smartaudio_protocol.c

Modified target define so that other vendors can add their own vtx targets.

Modified target define

---

src/hardware.c
src/msp_displayport.c
src/print.h

Fix keil issue

---

src/hardware.c
src/lifetime.c
src/msp_displayport.c
src/smartaudio_protocol.c

Warning does not harm always but it is good to fix those when possible :) 
Contains also some compilation error fixes with specific flags enabled.

Fix SDCC compilation errors and warnings

---

src/hardware.c
src/i2c_device.c
src/i2c_device.h

- Support for new batches of kaypad.
- There are very few very old kaypads that will no longer be supported because of some conflicts.

update keypad driver

---

.github/workflows/build.yml

updates all the relevant packages and syntax

fix gh-action warnings

---

src/msp_displayport.c

fix vtx lock check

---

src/camera.c
src/camera.h
src/hardware.c
src/hardware.h
src/mcu.c

remove video detect for some kinds of camera.

fix-video-regular-missing-issue

---

src/msp_displayport.c
src/msp_displayport.h

replaced some magic numbers with the corresponding defines
adjusted some define names as well and added some comment to them

msp define cleanup

---

src/runcam.c

add some delay for setting runcam camera shutter

 Fix "drunk camera" issue

---

src/hardware.c

- cannot detect foxeer digisight v3, blue led off
- if camera lost, blue led off

fix camera lost flag for blue led

---

README.md

added basic VTX troubleshooting.
add colon to Attention: section

Update README.md -added basic VTX troubleshooting.

---

src/common.h
src/hardware.c

Freq offset has been there from day one so it is time to fix the R2 frequency.

Fix R2 frequency and RaceV3 build warnings

---

src/dm6300.c
src/dm6300.h
src/hardware.c
src/hardware.h
src/mcu.c

if dm6300 lost, led will fast flash 2 times every second.

---

src/msp_displayport.c

fix parse_vtx_band_and_channel

---

src/msp_displayport.c

This fault was introduced by https://github.com/hd-zero/hdzero-vtx/pull/193

fix inav uart connection timeout

---

src/runcam.c

Fixing inverted V flip and H flip as suggested by Ligen

Fixing inverted V flip and H flip
